let e = document.getElementsByClassName('exercisea')[0]
e.innerHTML += 'Input: aBc, <br/>';

function cycle(s){
    function nextLetter(l){
        let code = l.charCodeAt(0);
        if (code===122){
            code = 97;
        } else if (code === 90){
            code = 65;
        } else if(code === 57){
            code = 48;
        } else{
            code++;
        }
        l = String.fromCharCode(code);
        return l;
    }
    s = s.replace(/[A-Za-z0-9]/g,nextLetter);
    return s;
}


e.innerHTML += `Output: ${cycle('aBc')}.`;
e.innerHTML += '<br/> <br/>';
e.innerHTML += `Input: xyz, <br/> Output: ${cycle('xyz')}`;
e.innerHTML += '<br/> <br/>';
e.innerHTML += `Input: aK89, <br/> Output: ${cycle('aK89')}`;

// ###############################################################
document.getElementById('userword').value = 'Lisa'; 
let t = document.getElementById("text");
let originalText = t.innerHTML;
function replaceWord(){
    w = document.getElementById('userword').value;
    let s = '\\b'+w+'\\b';
    let regex = new RegExp(s,"gm");
    newText = originalText.replaceAll(regex, `<a href="https://twitter.com/search?q=${w}">#${w}</a>`);
    t.innerHTML = newText;
    
}
b = document.getElementById("wordb");
b.addEventListener("click", replaceWord, false);
// ####################################################################
let c = document.getElementsByClassName('exercisec')[0]
let someText = 'Some words: new, cat, repaper, rotator, advanced, company, rotor, sagas, solos, stats, tenet, house, car, run';
c.innerHTML += someText;


function isPalindrome(s){
    s = s.toLowerCase();
    let len = Math.floor(s.length/2);
    let exp='';
    for (let i = 0; i < len; i++){
        exp += '(.)';
    }
    if ( !(len === s.length/2)) exp += '(.)';
    for(let i = len; i>0; i--){
        exp += `\\${i}`;
    }
    let regex = new RegExp(exp,"gm");
    let palindrome = s.match(regex);
    return Boolean(palindrome);
}

function getPalindromes(t){
    t = t.replaceAll(',', '').replaceAll('.','').replaceAll(':','').replaceAll(';','');
    t = t.replaceAll('!','').replaceAll('?','');
    let words = t.split(' ');
    let palindromes = [];
    for(word of words){
        if (isPalindrome(word)) palindromes.push(word);
    }
    return palindromes;
}

c.innerHTML += '<br/>';
c.innerHTML += 'From which we have the palidromes: '
if (getPalindromes(someText)){
    for (word of getPalindromes(someText)){
        c.innerHTML += `${word}, `
    }
}
c.innerHTML = c.innerHTML.slice(0,c.innerHTML.length-2);

// ####################################################################
let o = document.getElementsByClassName('exerciseo')[0]
o.innerHTML += 'Original paragraph: <br/> <br/>';
let paragraph = 'A match is a tool for starting a fire. Typically, matches are made of small wooden sticks or stiff paper. One end is coated with a material that can be ignited by frictional heat generated by striking the match against a suitable surface.[1] Wooden matches are packaged in matchboxes, and paper matches are partially cut into rows and stapled into matchbooks. The coated end of a match, known as the match "head", consists of a bead of active ingredients and binder; often colored for easier inspection. There are two main types of matches: safety matches, which can be struck only against a specially prepared surface, and strike-anywhere matches, for which any suitably frictional surface can be used.';
o.innerHTML += paragraph;

o.innerHTML += '<br/> <br/>';
o.innerHTML += 'Translated paragraph: <br/> <br/>';

function leetS(s){
    let translator = {'a':'4','b':'|3','c':'(','d':'|)','e':'3','f':'|=','g':'9','h':'#',
    'i':'!', 'j':'_|','k':'|<', 'l':'1','m':'|\\/|','n':'|\\|','o':'0', 'p':'|>','q':'<|',
    'r':'|2','s':'$','t':'7', 'u':'(_)','v':'\\/','w':'\\|/','x':'><','y':'`/', 'z':'2',
    ' ': ' &nbsp;&nbsp;'};
    s = s.toLowerCase();
    for (let l in translator){
        s = s.replaceAll(l, translator[l]);
    }
    return s;
}
let newParagrap = leetS(paragraph);    
o.innerHTML += newParagrap;